@extends('layouts.app')

@section('title', 'Pembayaran - ' . $order->order_number)

@section('content')

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="text-center mb-4">
            <div class="mb-3" style="font-size: 4rem;">✅</div>
            <h2 class="fw-bold">Pesanan Berhasil Dibuat!</h2>
            <p class="text-muted">Silakan lakukan pembayaran untuk memproses pesanan Anda</p>
        </div>

        <div class="row g-4">
            <!-- QRIS Payment -->
            <div class="col-md-6">
                <div class="qris-container">
                    <h5 class="fw-bold mb-3">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/QRIS_logo.svg/320px-QRIS_logo.svg.png" 
                             alt="QRIS" 
                             style="height: 30px;">
                    </h5>
                    
                    <p class="text-muted small mb-3">Scan QR code di bawah dengan aplikasi e-wallet atau m-banking Anda</p>
                    
                    <!-- QRIS QR Code (Demo - would be generated by Midtrans) -->
                    <div class="qris-code-wrapper mb-3">
                        <img src="https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=JEYCOOKIE-{{ $order->order_number }}-{{ $order->total }}" 
                             alt="QRIS Code" 
                             class="img-fluid rounded"
                             style="max-width: 250px;">
                    </div>
                    
                    <div class="amount-display p-3 bg-pink-50 rounded-3 mb-3">
                        <small class="text-muted">Total Pembayaran</small>
                        <h3 class="fw-bold text-pink mb-0">{{ $order->formatted_total }}</h3>
                    </div>
                    
                    <div class="alert alert-info small">
                        <i class="fa-solid fa-info-circle me-1"></i>
                        QR Code berlaku selama 24 jam
                    </div>
                    
                    <!-- Confirm Payment Button (Manual for demo) -->
                    <form action="{{ route('checkout.confirm', $order) }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-pink btn-lg w-100">
                            <i class="fa-solid fa-check-circle me-2"></i> Saya Sudah Bayar
                        </button>
                    </form>
                </div>
            </div>

            <!-- Order Details -->
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <i class="fa-solid fa-receipt me-2"></i> Detail Pesanan
                    </div>
                    <div class="card-body">
                        <table class="table table-borderless mb-0">
                            <tr>
                                <td class="text-muted">No. Pesanan</td>
                                <td class="text-end fw-semibold">{{ $order->order_number }}</td>
                            </tr>
                            <tr>
                                <td class="text-muted">Tanggal</td>
                                <td class="text-end">{{ $order->created_at->format('d M Y, H:i') }}</td>
                            </tr>
                            <tr>
                                <td class="text-muted">Status</td>
                                <td class="text-end">
                                    <span class="badge {{ $order->status_badge_class }}">
                                        {{ ucfirst($order->status) }}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td class="text-muted">Pembayaran</td>
                                <td class="text-end">
                                    <span class="badge {{ $order->payment_badge_class }}">
                                        {{ ucfirst($order->payment_status) }}
                                    </span>
                                </td>
                            </tr>
                        </table>
                        
                        <hr>
                        
                        <h6 class="fw-semibold mb-2">Item Pesanan</h6>
                        @foreach($order->items as $item)
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <span>
                                    {{ $item->product_name }}
                                    <small class="text-muted">x{{ $item->quantity }}</small>
                                </span>
                                <span>{{ $item->formatted_subtotal }}</span>
                            </div>
                        @endforeach
                        
                        <hr>
                        
                        <div class="d-flex justify-content-between">
                            <span class="text-muted">Subtotal</span>
                            <span>{{ $order->formatted_subtotal }}</span>
                        </div>
                        <div class="d-flex justify-content-between">
                            <span class="text-muted">Ongkir</span>
                            <span>Rp {{ number_format($order->delivery_fee, 0, ',', '.') }}</span>
                        </div>
                        <hr>
                        <div class="d-flex justify-content-between">
                            <span class="fw-bold">Total</span>
                            <span class="fw-bold text-pink">{{ $order->formatted_total }}</span>
                        </div>
                    </div>
                </div>

                <!-- Shipping Info -->
                <div class="card mt-3">
                    <div class="card-header">
                        <i class="fa-solid fa-truck me-2"></i> Alamat Pengiriman
                    </div>
                    <div class="card-body">
                        <p class="fw-semibold mb-1">{{ $order->customer_name }}</p>
                        <p class="text-muted mb-1">{{ $order->customer_phone }}</p>
                        <p class="text-muted mb-0">{{ $order->customer_address }}</p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Payment Instructions -->
        <div class="card mt-4">
            <div class="card-header">
                <i class="fa-solid fa-list-check me-2"></i> Cara Pembayaran
            </div>
            <div class="card-body">
                <ol class="mb-0">
                    <li class="mb-2">Buka aplikasi e-wallet atau m-banking Anda (GoPay, OVO, Dana, ShopeePay, BCA Mobile, dll)</li>
                    <li class="mb-2">Pilih menu <strong>Scan QR</strong> atau <strong>Bayar</strong></li>
                    <li class="mb-2">Scan QR Code yang ditampilkan di halaman ini</li>
                    <li class="mb-2">Pastikan nominal pembayaran sesuai: <strong>{{ $order->formatted_total }}</strong></li>
                    <li class="mb-2">Konfirmasi pembayaran di aplikasi Anda</li>
                    <li>Setelah berhasil, klik tombol <strong>"Saya Sudah Bayar"</strong></li>
                </ol>
            </div>
        </div>

        <div class="text-center mt-4">
            <a href="{{ route('orders.index') }}" class="btn btn-outline-pink">
                <i class="fa-solid fa-box me-2"></i> Lihat Pesanan Saya
            </a>
        </div>
    </div>
</div>

@endsection

@push('styles')
<style>
    .text-pink {
        color: var(--pink-600);
    }
    
    .bg-pink-50 {
        background: var(--pink-50);
    }
    
    .qris-code-wrapper {
        background: white;
        padding: 1rem;
        display: inline-block;
        border-radius: var(--radius-lg);
        box-shadow: var(--shadow);
    }
</style>
@endpush
